darkube_build_behtarino-admin_behtarino:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - export IMAGE="registry.hamdocker.ir/behtarino/behtarino-admin"
  - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG  --workdir
    . --file ./Dockerfile --build-context . '
  stage: build
darkube_build_dev-admin_behtarino-bht-dev:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - develop
  script:
  - export IMAGE="registry.hamdocker.ir/behtarino/dev-admin"
  - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG  --workdir
    . --file ./Dockerfile --build-context . '
  stage: build
darkube_deploy_behtarino-admin_behtarino:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - darkube deploy --ref main --token ${DARKUBE_behtarino_admin_behtarino_DEPLOY_TOKEN}
    --app-id ${DARKUBE_behtarino_admin_behtarino_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
    --job-id "${CI_JOB_ID}" --stateless-app true
  stage: deploy
darkube_deploy_dev-admin_behtarino-bht-dev:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - develop
  script:
  - darkube deploy --ref main --token ${DARKUBE_dev_admin_behtarino_bht_dev_DEPLOY_TOKEN}
    --app-id ${DARKUBE_dev_admin_behtarino_bht_dev_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
    --job-id "${CI_JOB_ID}" --stateless-app true
  stage: deploy
